import { StyleSheet, Text, View } from 'react-native'
import React from 'react'

export const styles = StyleSheet.create({
    ContainerAddCard:{
        flex:1,
        backgroundColor:'#fff'
    },
    ViewContainerAddCard:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        borderBottomWidth:1,
        paddingHorizontal:15
    },
    ViewHeaderContainer:{
        flexDirection:'row',
        alignItems:'center',
        marginVertical:15,
    },
    TextAddCard:{
        marginStart:10,
        fontSize:18,
        fontWeight:'700',

    },
    ViewContainerSecurity:{
        flexDirection:'row',
        alignItems:'center',
        borderWidth:1,
        width:120,
        borderRadius:30,
        justifyContent:'space-between',
        paddingHorizontal:5,
        backgroundColor:'#28f78f'
    },
    TextSecurityPayment:{
        width:55,
        fontWeight:'600'
    },
    ViewSecurity:{
        width:30,
        height:30,
        backgroundColor:'#21801b',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:15,
        // marginLeft:5
    },
    ViewContainerMain:{
        marginHorizontal:10,
        flex:1
    },
    ViewContainerNumberCard:{
        marginTop:25,
    },
    TextNumberCard:{
        fontWeight:'600',
        fontSize:16,
    },
    TextInputInformation:{
        borderBottomWidth:1,
        fontSize:16, 
        paddingBottom:-10
    },
    ViewInformationCard:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginVertical:20,
    },
    ViewInformation:{
        width:"50%",
        paddingLeft:10
    },
    ViewContentDeduction:{
        flexDirection:'row',
        backgroundColor:'#e9ede8',
        borderRadius:10,
        padding:10,
        alignItems:'center'
    },
    ImageCard:{
        width:30,
        height:30,
        marginHorizontal:10
    },
    TextContent:{
        width:'85%',
        marginStart:10,
        fontSize:14,
    },
    ViewContainerButtonSave:{
        marginHorizontal:10,
        marginVertical:20,
    },
    ViewContentSave:{
        flexDirection:'row',
        alignItems:'center'
    },
    TextSave:{
        marginStart:5
    },
    TextCondition:{
        color:"#089629",
        fontWeight:'700'
    },
    ButtonSave:{
        backgroundColor:'#089629',
        justifyContent:'center',
        alignItems:'center',
        paddingVertical:10,
        borderRadius:45,
        marginTop:10
    },
    TextSaveCard:{
        fontWeight:'800',
        fontSize:18,
        color:'white'
    }

})