import {StyleSheet, Text, View} from 'react-native';
import {Color, Size, FontWeight, FontFamily} from '../../../constants/theme';
export const styles = StyleSheet.create({
  buttonIcon: {
    width: 45,
    height: 45,
    backgroundColor: Color.bgItem,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewIcon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    zIndex: 5,
    width: '100%',
    padding: 15,
  },
  viewContainerImage: {
    borderWidth: 1,
    borderRadius: 15,
    borderColor: Color.primary1,
    overflow: 'hidden',
    height: 220,
    backgroundColor: Color.white,
    width: '100%',
    marginBottom:20
  },
  imageAvatar: {
    width: 68,
    height: 68,
    borderRadius: 68,
    position: 'absolute',
    top: -30,
  },
  textSumbmitReview: {
    color: '#333',
    fontSize: 18,
    fontWeight: '700',
  },
  buttonSubmitReview: {
    alignItems: 'center',
    backgroundColor: '#29D8E4',
    borderRadius: 12,
    paddingVertical: 16,
    marginHorizontal: 18,
    marginBottom: 70,
    marginTop: 46,
  },
  textInputSubmitReview: {
    color: '#74788C',
    fontSize: 12,
    fontWeight: '400',
    padding: 10,
  },
  viewContainerInput: {
    height: 151,
    borderRadius: 15,
    backgroundColor: '#FFF9E6',
    marginTop: 23,
    width: '100%',
    marginBottom: 17,
    borderWidth: 1,
    borderColor: '#EBA078',
    position:'relative'
  },
  textNumberStarRating: {
    marginTop: 5,
    color: Color.text,
    fontSize: 12,
    fontWeight: FontWeight.FW400,
  },
  textReviewCustomer: {
    color: Color.textBold,
    fontSize: Size.S20,
    fontWeight: FontWeight.FW700,
    marginTop:15
  },
  viewContainerReviewCustomer: {
    alignItems: 'center',
    backgroundColor: '#F2F2F2',
    borderRadius: 15,
    paddingHorizontal: 23,
    position: 'relative',
    marginHorizontal: 16,
    borderBottomWidth:1,
    borderColor:'#DFDFDF',
    marginTop:10
  },
  buttonHeaderHome:{
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: '#F5FEFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  textTitleHeader:{
    color: '#005987',
    fontSize: 20,
    fontWeight: '700',
  },
  viewContainerHeader:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    borderBottomWidth: 1,
    borderBlockColor: '#5C94B2',
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  viewContainer: {
    flex: 1,
    backgroundColor: Color.white,
    fontFamily: FontFamily.poppins,
  },
});
